### ISSUE TITLE
.net core API

### ISSUE THREAD

**Issue by ashwinianbhore** [xBimTeam/XbimGltf#6]
are those libraries available for .net core ?

**Comment by andyward** [comment]
I think that could be a way off since this plugin library is dependent on Xbim.Windows UI which is in turn dependent on Xbim.Geometry. Both of these packages still only support netframework. Windows UI is WPF (so we'd need to implement https://github.com/xBimTeam/XbimWindowsUI/issues/131) while the Geometry needs a major refactor to support multi-platform.

That said, if you just wanted to undertake IFC=>GLTF, I think we should look to move the GLTF IO export code down the stack. Logically it could sit along side https://github.com/xBimTeam/XbimEssentials/blob/master/Xbim.Ifc/Extensions/IfcStoreGeometryExtensions.cs

... leaving this repo as the WPF plugin side of things.

Splitting this functionality up would let non-WPF clients (maybe on netcore) output to a GLTF format. (With a proviso that the geometry would need to be processed under Windows net framewortk)

**Comment by ashwinianbhore** [comment]
Thanks

**Comment by CBenghi** [comment]
At the moment the code is separated in two projects. 
Only the plugin UI relies on WIndowsUI, the other is just based on Essentials to read the geometry for conversion.
However it's granted that there's a requisite of Geometry for the meshing process.
The export could be at essentials level provided that we have a non-windows geometry storage system.
